package FileManager;

import FileSystem.FileSystem;

import javax.swing.*;
import java.awt.*;

public class FileManagerDialog extends JDialog {
    private FileSystem fileSystem;

    private JPanel contentPane;
    private JPanel fileManagerLeftPanel;
    private JPanel fileManagerRightPanel;
    private JPanel sectorsPanel;
    private JPanel controlsPanel;

    public FileManagerDialog() {
        fileSystem = new FileSystem(64, 65536);
        $$$setupUI$$$();
        setContentPane(contentPane);
        setModal(true);
    }

    public static void main(String[] args) {
        FileManagerDialog dialog = new FileManagerDialog();
        dialog.pack();
        dialog.setVisible(true);
        System.exit(0);
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        createUIComponents();
        contentPane = new JPanel();
        contentPane.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(3, 2, new Insets(10, 10, 10, 10), -1, -1));
        contentPane.setMaximumSize(new Dimension(1000, 650));
        contentPane.setMinimumSize(new Dimension(1000, 650));
        contentPane.setOpaque(true);
        contentPane.setPreferredSize(new Dimension(1000, 650));
        final JScrollPane scrollPane1 = new JScrollPane();
        scrollPane1.setHorizontalScrollBarPolicy(31);
        scrollPane1.setVerticalScrollBarPolicy(22);
        contentPane.add(scrollPane1, new com.intellij.uiDesigner.core.GridConstraints(0, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_BOTH, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, new Dimension(40, 40), new Dimension(400, 400), new Dimension(500, 1000), 0, false));
        fileManagerLeftPanel.setAutoscrolls(false);
        scrollPane1.setViewportView(fileManagerLeftPanel);
        final JScrollPane scrollPane2 = new JScrollPane();
        scrollPane2.setHorizontalScrollBarPolicy(31);
        scrollPane2.setVerticalScrollBarPolicy(22);
        contentPane.add(scrollPane2, new com.intellij.uiDesigner.core.GridConstraints(0, 1, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_BOTH, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, new Dimension(40, 40), new Dimension(400, 400), new Dimension(500, 1000), 0, false));
        scrollPane2.setViewportView(fileManagerRightPanel);
        contentPane.add(sectorsPanel, new com.intellij.uiDesigner.core.GridConstraints(1, 0, 1, 2, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_BOTH, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, null, new Dimension(-1, 200), null, 0, false));
        contentPane.add(controlsPanel, new com.intellij.uiDesigner.core.GridConstraints(2, 0, 1, 2, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_BOTH, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, null, new Dimension(-1, 200), null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return contentPane;
    }

    private void createUIComponents() {
        fileManagerLeftPanel = new FileManagerPanel(fileSystem);
        fileManagerRightPanel = new FileManagerPanel(fileSystem, (FileManagerPanel) fileManagerLeftPanel);
        ((FileManagerPanel) fileManagerLeftPanel).setOtherPanel((FileManagerPanel) fileManagerRightPanel);
        sectorsPanel = new SectorsPanel(fileSystem, (FileManagerPanel) fileManagerLeftPanel, (FileManagerPanel) fileManagerRightPanel);
        ((FileManagerPanel) fileManagerRightPanel).setSectorsPanel((SectorsPanel) sectorsPanel);
        ((FileManagerPanel) fileManagerLeftPanel).setSectorsPanel((SectorsPanel) sectorsPanel);
        controlsPanel = new ControlsPanel(fileSystem, (FileManagerPanel) fileManagerLeftPanel, (FileManagerPanel) fileManagerRightPanel, (SectorsPanel) sectorsPanel);

    }
}
